apiVersion: v2
name: ai-detector
description: AI Product Photo Detector - Detect AI-generated product images
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ai
  - ml
  - image-classification
  - product-detection
  - mlops
maintainers:
  - name: Nolan Cacheux
    email: cachnolan@gmail.com
    url: https://github.com/nolancacheux
home: https://github.com/nolancacheux/mlops_project
sources:
  - https://github.com/nolancacheux/mlops_project
