apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-detector

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - storage.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: ai-detector
  app.kubernetes.io/part-of: ai-detector
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/nolancacheux/ai-detector
    newTag: latest
  - name: ghcr.io/nolancacheux/ai-detector-ui
    newTag: latest
